server:
  port: 8040
spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false


zuul:
  routes:
    user-route:
      url: http://192.168.1.101:5555
      path: /baidu/**