server:
  port: 8040
spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false


zuul:
  routes:
    user-route:
      path: /baidu/**
      service-id: baidu
ribbon:
  eureka:
    enabled: false
baidu:
  ribbon:
    listOfServers: www.baidu.com,www.baidu.com