spring:
  application:
    name: eureka-server-ha
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8761/eureka/
---
spring:
  profiles: node1
server:
  port: 8761
---
spring:
  profiles: node2
server:
  port: 8762
